### ISSUE TITLE
一点点小小的看法～=￣ω￣=～

### ISSUE THREAD

**Issue by BuptStEve** [Molunerfinn/Nodejs-ByrTopTen#1]
- 其实可以爬 [北邮人论坛移动版](http://m.byr.cn) ,你这样用 rss 我总觉得怪怪的╮(╯_╰)╭
- 可以试试 [node-cron](https://github.com/merencia/node-cron) 用 crontab 写法,感觉更优雅一点儿...
- 数据保存就提前安利一下 mongoDB 咯～=￣ω￣=～

**Comment by Molunerfinn** [comment]
- 哈哈，其实我主要做的只是保存每天的十大啦。rss直接就能做到我拿到所需的所有信息（对，我并没有打算爬评论）。
- crontab的写法我看了，node-schedule也是支持的。所以到时候要改。因为当时仓促，没有看过crontab，所以直接写成这样。
- 数据保存，我最近一直在看mongodb的！所以我近期的工作就在整理一下数据存mongodb去，基本上现在就差存进去和读出来了，页面的构思差不多了。不过还有些细节方面的东西，感觉得放到第二个版本去跟进。
  谢谢关心哈哈哈~！

**Comment by BuptStEve** [comment]
我一开始也是用 node-schedule 不过貌似有 bug...我才又搜到 node-cron ,简单一用发现还行...╮(╯_╰)╭

ps 你参加那啥 ife 的么?

**Comment by Molunerfinn** [comment]
嗯，有这个打算。。
